'dz4'
oldborrow/todolist pull request #2
Opened 2020-10-25 19:21 UTC by oldborrow

Нужна помощь, я не понимаю как передать данные из oneComponent в App, чтобы добавить новую задачу в список. Еще не понимаю, как сделать так чтобы после изменения completed менялось само его отображение на экране. Вроде больше больших проблем нет, все что вы писали из замечаний в дз 3 постарался исправить. Спасибо

2020-10-26 11:14 UTC, ValeryStatinov commented
> Нужна помощь, я не понимаю как передать данные из oneComponent в App, чтобы добавить новую задачу в список. Еще не понимаю, как сделать так чтобы после изменения completed менялось само его отображение на экране. Вроде больше больших проблем нет, все что вы писали из замечаний в дз 3 постарался исправить. Спасибо

PR пока что не смотрел.
по поводу вопросов:
* передать данные из oneComponent в App - посмотри последний слайд 4ого семинара + hint: ф-ии можно передавать в качестве props
* hint: ф-ии можно передавать в качестве props

2020-10-29 15:00 UTC, oldborrow commented
Добавил все что нужно, кроме двух вещей:
1) Не получается сделать так, чтобы при клике на кнопку значение completed менялось на противоположное, сейчас меняется только с false на true. Пробовал делать через ифы/тернарные операторы/доп переменную, все равно не выходит
2) Это нормально, что после добавления таска окно добавления исчезает? Если нет, то как это можно исправить? Спасибо!

2020-11-06 11:21 UTC, oldborrow commented
@ValeryStatinov

2020-11-12 16:09 UTC, ValeryStatinov requested changes

2020-11-12 16:09 UTC, ValeryStatinov commented on src/App.js
> +      newTasks.find(item => item.id === id).completed = true
во 1ых - мутация данных. newTasks - это новый массив, но все объекты внутри него прежние,  тк spread operator делает shallow копирование
```javascript
const newTasks = [...currentState.tasks]
const index = newTasks.findIndex(t => t.id === id)
newTasks[index] = { ...newTasks[index], completed: true/false }
```

во 2ых - ты выставляешь только значение `true`, поэтому только с false на true и менятеся)
в прошлом код сниппете
```javascript
const newCompeleted = !newTasks[index].completed
```

2020-11-12 16:09 UTC, ValeryStatinov commented on src/TaskAdd.js
> +        }))
здесь ты ставишь `hideTask` в `true`. а ниже в render пишешь `{!this.state.hideTask && <input value = {this.state.name} onChange = {this.handleNameChange}/>}` и тд. поэтому добавление и пропадает. нужно просто избавиться от этой переменной в стейте и добавление пропадать не будет

2020-11-12 20:04 UTC, merged

2020-11-12 21:01 UTC, oldborrow commented
Спасибо большое, все исправил и случайно запушил в другую ветку dz5

2020-11-13 12:31 UTC, ValeryStatinov commented
мерджу пулл реквесты я. это означает, что дз засчитано и оценка поставлена в таблицу. теперь тебе нужно повоевать с гитом:
* ревертнуть этот PR
* открыть новый PR с дз4 со всем фиксами
* в описании нового PR на дз4 оставить ссылку на этот, чтобы я проставил правильную дату выполнения дз в таблицу и не применились штрафы

2020-11-13 13:50 UTC, oldborrow commented
я вчера открыл PR dz5, там все фиксы есть, сейчас поменял его название на dz4 и ссылку добавил в описание, норм?

2020-11-13 13:59 UTC, ValeryStatinov commented
лучше сделать все правильно, как я описал. мне будет проще проверять, а ты прокачаешь скиллы гита, что полезно в любом случае

2020-11-13 15:14 UTC, oldborrow commented
теперь точно должно быть правильно

2020-11-13 15:41 UTC, ValeryStatinov commented
🤯точно должно быть, но неправильно. вот тут https://github.com/oldborrow/todolist/pull/7/files изменения явно не те, которые мне нужно просматривать и оценивать. + ты сам мерджил PR с 3ей дз и по итогу у тебя нет оценки за нее в таблице https://docs.google.com/spreadsheets/d/1O53IFdbwqZ6qRuBQRbrg6PY9T2hY1rO2Zmi4a-JwBvk/edit#gid=0

что нужно теперь сделать:
* локально у тебя должны были остаться ветки с 3ей и с 4ой дз
* ресетнуть main до начального состояния (начальным считается то, которое создает create-react-app)
* открыть PR с ветки hw3 на main, чтобы я еще раз проверил дз3 и поставил оценку в таблицу
* открыть PR с ветки hw4 на main, чтобы я еще раз проверил дз4 и поставил оценку в таблицу

при возникновении вопросов и проблемы можно обращаться в чат. там есть студенты, которые могут помочь с гитом

2020-11-15 13:33 UTC, oldborrow commented
Пожалуйста, проверьте мое дз так, у меня несколько компьютеров и я запутался в версиях, не могу найти старые и восстановить их, но они же лежали тут две недели. Может сможете сделать исключение и проверить по последнему PR?

2020-11-16 11:51 UTC, oldborrow commented
Можете подсказать, хотя бы дз 5 я правильно сдал?

2020-11-28 14:36 UTC, oldborrow commented
@ValeryStatinov